# Generated by Django 4.2.7 on 2026-02-22 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('novels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('start_offset', models.IntegerField()),
                ('end_offset', models.IntegerField()),
                ('color', models.CharField(choices=[('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('pink', 'Pink'), ('orange', 'Orange')], default='yellow', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='novels.chapter')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='novels.novel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'highlights',
                'ordering': ['chapter', 'start_offset'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page', models.IntegerField(default=0)),
                ('position', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='novels.chapter')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='novels.novel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookmarks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_page', models.IntegerField(default=0)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('reading_time_minutes', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='novels.chapter')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to='novels.novel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reading_progress',
                'ordering': ['-last_read_at'],
                'indexes': [models.Index(fields=['user', '-last_read_at'], name='reading_pro_user_id_4bef0a_idx')],
                'unique_together': {('user', 'novel')},
            },
        ),
        migrations.CreateModel(
            name='ReadingAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('minutes_read', models.IntegerField(default=0)),
                ('pages_read', models.IntegerField(default=0)),
                ('chapters_completed', models.IntegerField(default=0)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='novels.novel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reading_analytics',
                'ordering': ['-date'],
                'unique_together': {('user', 'novel', 'date')},
            },
        ),
    ]
