# Generated by Django 4.2.7 on 2026-02-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='position',
            field=models.FloatField(default=0.0),
        ),
    ]
