# Generated by Django 4.2.7 on 2026-02-22 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('novels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField(default=0.0)),
                ('algorithm', models.CharField(choices=[('collaborative', 'Collaborative Filtering'), ('content_based', 'Content-Based Filtering'), ('hybrid', 'Hybrid'), ('rule_based', 'Rule-Based'), ('trending', 'Trending')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('is_seen', models.BooleanField(default=False)),
                ('is_clicked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='novels.novel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendations',
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='ReadingBehavior',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('view_count', models.IntegerField(default=0)),
                ('reading_sessions', models.IntegerField(default=0)),
                ('total_time_minutes', models.IntegerField(default=0)),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_favorited', models.BooleanField(default=False)),
                ('rated', models.IntegerField(blank=True, null=True)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to='novels.novel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_behaviors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reading_behaviors',
                'unique_together': {('user', 'novel')},
            },
        ),
        migrations.CreateModel(
            name='GenrePreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preference_score', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='novels.genre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'genre_preferences',
                'ordering': ['-preference_score'],
                'unique_together': {('user', 'genre')},
            },
        ),
    ]
